### ISSUE TITLE
Dockerized deploy

### ISSUE THREAD

**Issue by jrots** [spiral/app-grpc#1]
Hi, really like what you guys are doing with roadrunner and the modernized php framework 
Just more of a question, I see that the spiral binary is downloaded in this step : 

> composer create-project spiral/app-grpc

and is really platform specific from where it is run ( if I run this on mac f.e. )

> Updating binary file of Spiral Server
Downloading Spiral Server archive for Darwin

As most modern php apps run in lambda/ docker containers, 
is there a specific deployment flow or documentation on how to setup these apps so that the spiral binary is suitable for the platform where it's run?

**Comment by wolfy-j** [comment]
Yes, it is specific to the platform it run on. You can use the following docker template:
https://github.com/n1215/roadrunner-docker-skeleton
or this one:
https://github.com/spiral/roadrunner/blob/master/Dockerfile

We are going to release an official docker package with the next RoadRunner release.

About Lambda - you will have to build custom runtime (see our wiki how to do that). So it will involve manual binary compilation one way or another. We might simplify it in the future but Lambda optimized deployments are not in priority for us now.

**Comment by jrots** [comment]
thx will check it out!
